title: Earn Money Online
description: A website with a blog
footer_text: Copyright 2023 Earn Money Online
header_feature_image: ../uploads/earnonlinemoney-sleep.png
header_text: Earn Money Online
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
